Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using sistemaDeAdocaoParaAnimais.Helper;
using sistemaDeAdocaoParaAnimais.Models;
using sistemaDeAdocaoParaAnimais.Services;

namespace sistemaDeAdocaoParaAnimais.Controllers
{
    public class AlterarSenhaController : Controller
    {

        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;
        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenha alterarSenha)
        {
            try
            {
                Usuarios usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenha.Id = usuarioLogado.UsuarioId;
                
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenha);
                    TempData["MensagemSucesso"] = $"Senha alterada com sucesso";
                }
                return View("Index", alterarSenha);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha, tente novamente.";
                return View("Index", alterarSenha);
            }
        }
    }
}

Controllers/AnimaisController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.ML;
using sistemaDeAdocaoParaAnimais.Helper;
using sistemaDeAdocaoParaAnimais.Models;

namespace sistemaDeAdocaoParaAnimais.Controllers
{
    public class AnimaisController : Controller
    {
        private readonly SistemaDeAdocaoParaAnimaisContext _context;
        private readonly ISessao _sessao;

        public AnimaisController(SistemaDeAdocaoParaAnimaisContext context, ISessao sessao)
        {
            _context = context;
            _sessao = sessao;
        }

        [HttpPost]
        public async Task<IActionResult> Limpar()
        {

            IEnumerable<Animal> petsDisponiveis = new List<Animal>(_context.animals.Where(a => a.EstadoAdocaoPet == "Disponível"));
            return View(petsDisponiveis);
        }

        [HttpPost]
        public async Task<IActionResult> Buscar(string sexo, string estado, string porte)
        {

            IEnumerable<Animal> petsDisponiveis = new List<Animal>(_context.animals.Where(a => a.EstadoAdocaoPet == "Disponível"));
            if (sexo != "Todos os sexos")
            {
                petsDisponiveis = petsDisponiveis.Where(a => a.Sexo == sexo);
            }
            if (estado != "Todos os estados")
            {
                petsDisponiveis = petsDisponiveis.Where(a => a.Estado == estado);
            }

            if (porte != "Todos os Portes")
            {
                petsDisponiveis = petsDisponiveis.Where(a => a.Porte == porte);
            }

            return View(petsDisponiveis);
        }


        public async Task<IActionResult> ExibirPet(int? id)
        {
            var informacoesAnimal = _context.animals.Find(id);
            var inforUser = _context.usuarios.Find(informacoesAnimal.FkUsuarios);
            var user = _context.usuarios.Where(a => a.UsuarioId == inforUser.UsuarioId);
            ViewBag.user = user;

            IEnumerable<Animal> pets = new List<Animal>(_context.animals.Where(a => a.Id == id));
            return View(pets);
        }


        public async Task<IActionResult> Buscar()
        {

            Usuarios usuario1 = _sessao.BuscarSessaoDoUsuario();
            var usuario = _context.usuarios.Find(usuario1.UsuarioId);
            var caracteristicaUsuario = _context.caracteristicaUsuarios.Find(usuario.fkCaracteristica);

            BuscarFkUsuario();

            foreach (var animal in _context.animals)
            {
                string _dataPath = Path.Combine(Environment.CurrentDirectory, "Data", "CaracteristicaAnimal.csv");
                string _modelPath = Path.Combine(Environment.CurrentDirectory, "Data", "IrisClusteringModel.zip");

                var mlContext = new MLContext(seed: 0);

                IDataView dataView = mlContext.Data.LoadFromTextFile<CaracteristicaAnimal>(_dataPath, hasHeader: false, separatorChar: ',');

                string featuresColumnName = "Features";
                var pipeline = mlContext.Transforms
                    .Concatenate(featuresColumnName, "Energia", "Humor", "Apego", "Brincalhao", "Adestramento")
                    .Append(mlContext.Clustering.Trainers.KMeans(featuresColumnName, numberOfClusters: 3));

                var model = pipeline.Fit(dataView);

                using (var fileStream = new FileStream(_modelPath, FileMode.Create, FileAccess.Write, FileShare.Write))
                {
                    mlContext.Model.Save(model, dataView.Schema, fileStream);
                }

                var predictor = mlContext.Model.CreatePredictionEngine<CaracteristicaUsuario, ClusterPrediction>(model);

                CaracteristicaUsuarioTeste.caracteristicaUsuario.Apego = caracteristicaUsuario.Apego;
                CaracteristicaUsuarioTeste.caracteristicaUsuario.Humor = caracteristicaUsuario.Humor;
                CaracteristicaUsuarioTeste.caracteristicaUsuario.Energia = caracteristicaUsuario.Energia;
                CaracteristicaUsuarioTeste.caracteristicaUsuario.Adestramento = caracteristicaUsuario.Adestramento;
                CaracteristicaUsuarioTeste.caracteristicaUsuario.Brincalhao = caracteristicaUsuario.Brincalhao;

                var prediction = predictor.Predict(CaracteristicaUsuarioTeste.caracteristicaUsuario);
                Console.WriteLine($"Cluster: {prediction.PredictedClusterId}");
                Console.WriteLine($"Distances: {string.Join(" ", prediction.Distances)}");

                animal.FkCluster = prediction.PredictedClusterId;
                _context.Update(animal);
            }
            await _context.SaveChangesAsync();
            IEnumerable<Animal> petsDisponiveis = new List<Animal>(_context.animals.Where(a => a.FkCluster == usuario.FkCluster && a.EstadoAdocaoPet == "Disponível"));
            return View(petsDisponiveis);
        }

        public async void BuscarFkUsuario()
        {
            Usuarios usuario1 = _sessao.BuscarSessaoDoUsuario();

            var usuario = _context.usuarios.Find(usuario1.UsuarioId);

            var caracteristicaUsuario = _context.caracteristicaUsuarios.Find(usuario.fkCaracteristica);

            string _dataPath = Path.Combine(Environment.CurrentDirectory, "Data", "CaracteristicaAnimal.csv");
            string _modelPath = Path.Combine(Environment.CurrentDirectory, "Data", "CaracteristicaUsuarioModel.zip");

            var mlContext = new MLContext(seed: 0);

            IDataView dataView = mlContext.Data.LoadFromTextFile<CaracteristicaAnimal>(_dataPath, hasHeader: false, separatorChar: ',');

            string featuresColumnName = "Features";
            var pipeline = mlContext.Transforms
                .Concatenate(featuresColumnName, "Energia", "Humor", "Apego", "Brincalhao", "Adestramento")
                .Append(mlContext.Clustering.Trainers.KMeans(featuresColumnName, numberOfClusters: 3));

            var model = pipeline.Fit(dataView);

            using (var fileStream = new FileStream(_modelPath, FileMode.Create, FileAccess.Write, FileShare.Write))
            {
                mlContext.Model.Save(model, dataView.Schema, fileStream);
            }

            var predictor = mlContext.Model.CreatePredictionEngine<CaracteristicaUsuario, ClusterPrediction>(model);

            CaracteristicaUsuarioTeste.caracteristicaUsuario.Apego = caracteristicaUsuario.Apego;
            CaracteristicaUsuarioTeste.caracteristicaUsuario.Humor = caracteristicaUsuario.Humor;
            CaracteristicaUsuarioTeste.caracteristicaUsuario.Energia = caracteristicaUsuario.Energia;
            CaracteristicaUsuarioTeste.caracteristicaUsuario.Adestramento = caracteristicaUsuario.Adestramento;
            CaracteristicaUsuarioTeste.caracteristicaUsuario.Brincalhao = caracteristicaUsuario.Brincalhao;

            var prediction = predictor.Predict(CaracteristicaUsuarioTeste.caracteristicaUsuario);
            Console.WriteLine($"Cluster: {prediction.PredictedClusterId}");
            Console.WriteLine($"Distances: {string.Join(" ", prediction.Distances)}");

            usuario.FkCluster = prediction.PredictedClusterId;
        }

        // GET: Animais
        public async Task<IActionResult> Index()
        {
            var sistemaDeAdocaoParaAnimaisContext = _context.animals.Include(a => a.Usuarios);
            return View(await sistemaDeAdocaoParaAnimaisContext.ToListAsync());
        }

        // GET: Animais/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.animals == null)
            {
                return NotFound();
            }

            var animal = await _context.animals
                .Include(a => a.Usuarios)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnimalCaracteristica([Bind("Id,FkUsuarios, FkCaracteristicaAnimal, FkCluster, Nome,Raca,Cor,Descricao,Porte,Especie,Sexo,Estado,Cidade,Vacinado,Castrado,Vermifugado,EstadoAdocaoPet,ImagensPet")] Animal animal, float energia, float humor, float apego, float adestramento, float brincalhao)
        {
            if (ModelState.IsValid)
            {
                CaracteristicaAnimal caracteristicaAnimal = new CaracteristicaAnimal();
                caracteristicaAnimal.Energia = energia;
                caracteristicaAnimal.Apego = apego;
                caracteristicaAnimal.Humor = humor;
                caracteristicaAnimal.Adestramento = adestramento;
                caracteristicaAnimal.Brincalhao = brincalhao;
                _context.Add(caracteristicaAnimal);
                await _context.SaveChangesAsync();

                Usuarios usuario1 = _sessao.BuscarSessaoDoUsuario();
                animal.FkUsuarios = usuario1.UsuarioId;

                _context.Add(animal);
                await _context.SaveChangesAsync();

                animal.FkCaracteristicaAnimal = caracteristicaAnimal.Id;
                _context.Update(animal);
                await _context.SaveChangesAsync();

                return RedirectToAction("Profile", "Usuarios");
            }
            ViewData["FkUsuarios"] = new SelectList(_context.usuarios, "UsuarioId", "Nome", animal.FkUsuarios);
            return View(animal);
        }

        public IActionResult CreateAnimalCaracteristica()
        {
            ViewData["FkUsuarios"] = new SelectList(_context.usuarios, "UsuarioId", "Nome");
            return View();
        }

        // GET: Animais/Create
        public IActionResult Create()
        {
            ViewData["FkUsuarios"] = new SelectList(_context.usuarios, "UsuarioId", "Nome");

Views/Shared/Components/Menu/Default.cshtml
@model sistemaDeAdocaoParaAnimais.Models.Usuarios

<header class="header_wrapper">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a href="#" class="navbar">
                <img src="~/img/logopets.png" style="width: 90px;" alt="">
                <span style="color: white; font-size: 35px; font-family: Roboto;  font-weight: 800;">AnimalPets</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="#" class="nav-link"
                            style="color: white; font-size: 1.3rem; font-family: Roboto;  font-weight: 800;">Quero
                            adotar</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link"
                            style="color: white; font-size: 1.3rem; font-family: Roboto;  font-weight: 800;">Quero
                            cadastrar</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link"
                            style="color: white; font-size: 1.3rem; font-family: Roboto;  font-weight: 800;">Quero
                            ajudar</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link"
                            style="color: white; font-size: 1.3rem; font-family: Roboto;  font-weight: 800;">Parcerias</a>
                    </li>
                </ul>
            </div>
            <div class="dropdown" style="margin-left: 25px;">
                <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="@Html.DisplayFor(model => model.Avatar)" alt="Admin" id="avatar" class="circles"
                        width="80"><br>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                    style="width: 250px; height: 270px; margin-top: -22px;">
                    <li><a class="dropdown-item" style="font-size: 16px; font-weight: 500;" asp-controller="Animais"
                            asp-action="CreateAnimalCaracteristica">Cadastar novo
                            animal</a></li>
                    <li><a class="dropdown-item" style="font-size: 16px; font-weight: 500;" asp-controller="Usuarios"
                            asp-action="Profile">Meu perfil</a></li>
                    <li><a class="dropdown-item" style="font-size: 16px; font-weight: 500;" asp-controller="AlterarSenha"
                            asp-action="Index" asp-route-id="@Model.UsuarioId">Alterar Senha</a></li>
                    <li><a class="dropdown-item" style="font-size: 16px; font-weight: 500;" asp-controller="Usuarios"
                            asp-action="Edit" asp-route-id="@Model.UsuarioId">Editar Perfil</a></li>
                    <li><a class="dropdown-item" style="font-size: 16px; font-weight: 500;" asp-controller="Login"
                            asp-action="Sair">Sair</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>